name: Tests
on: [push]
jobs:
    test-build:
        runs-on: ubuntu-latest
        environment: test
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v3

          - name: Install Node
            uses: actions/setup-node@v3
            with:
              node-version: '16.11.1'

          - restore_cache:
              key: v1-deps-{{ checksum "package-lock.json" }}

          - name: Install Dependencies
              run: npm install
      # save any changes to the cache
          - save_cache:
              key: v1-deps-{{ checksum "package-lock.json" }}
              paths: 
               - node_modules  
          - run:
              name: Build
              command: |
                npm run build
          - run:
              name: Move Build to tmb
              command: |
                mkdir -p /tmp/workspace/build
                mv -v build/* /tmp/workspace/build
          - persist_to_workspace:
              root: /tmp/workspace
              paths:
                - build

# Necessary action when needing to use AWS credentials.
#          - name: Configure AWS Credentials
#            uses: aws-actions/configure-aws-credentials@v1
#            with:
#              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#              aws-region: us-west-1

